rule: |
  &a&lマイクラ鯖共通ルール
  &f・道のど真ん中に建築はしないでください。
  &f・荒らし・チート・ハッキングなどは禁止します。
  &f・ハッククライアントは使用しないでください。
  &f・人の家(敷地)に勝手に入らないでください
  &f・人を &n'わざと'&f 倒し、アイテムを略奪をすることを禁止します。
  &f・&c&lOPの指示に従ってください。
  &f・&cVPN/プロキシを&n経由&cしてアクセスしないでください