name: NekoHubv2
version: '${project.version}'
main: com.nekozouneko.nekohubv2.bukkit.NekoHubv2
api-version: 1.16
authors: [ Taitaitatata ]
description: NekoHub v2
website: "https://nekozouneko.ddns.net"

commands:
  move:
    description: "BungeeにNekoHubv2が導入されてる場合サーバー間移動が可能です。"
    usage: '/<command> <server> [target]'
    permission: NekoHubv2.cmd.move
    permission-message: "権限が不足しています。/serverコマンドを代わりに使用してください。"
  serverpanel:
    aliases: [ "sp", "servers"]
    description: "サーバーの選択パネルです。"
    usage: '/<command>'
  stickmenu:
    aliases: ["sm"]
    description: "棒メニューを表示します。"
    usage: '/<command>'
  stick:
    description: "棒を取得します。"
    usage: '/<command>'
  enderchest:
    aliases: ['ender', 'ec']
    description: "エンダーチェストを開けるだけ"
    usage: '/<command>'
  rule:
    aliases: ['r', 'readme']
    description: "ルールを見る"
    usage: '/<command>'