name: NekoHubv2
version: '${project.version}'
main: com.nekozouneko.nekohubv2.bukkit.NekoHubv2
api-version: 1.16
authors: ["Taitaitatata"]
description: NekoHub v2
website: "https://nekozouneko.ddns.net"
softdepend: ["LuckPerms"]

commands:
  move:
    description: "BungeeにNekoHubv2が導入されてる場合サーバー間移動が可能です。"
    usage: '/<command> <server> [target]'
    permission: NekoHubv2.cmd.move
    permission-message: "権限が不足しています。/serverコマンドを代わりに使用してください。"
  serverpanel:
    aliases: [ "sp", "servers"]
    description: "サーバーの選択パネルです。"
    permission: NekoHubv2.cmd.serverpanel
    usage: '/<command>'
  stickmenu:
    aliases: ["sm"]
    description: "棒メニューを表示します。"
    permission: NekoHubv2.cmd.stickmenu
    usage: '/<command>'
  stick:
    description: "棒を取得します。"
    permission: NekoHubv2.cmd.stick
    usage: '/<command>'
  enderchest:
    aliases: ['ender', 'ec']
    description: "エンダーチェストを開けるだけ"
    permission: NekoHubv2.cmd.enderchest
    usage: '/<command>'
  rule:
    aliases: ['r', 'readme']
    description: "ルールを見る"
    permission: NekoHubv2.cmd.rule
    usage: '/<command>'
  nekohubv2:
    aliases: ['nhv2', 'nh']
    description: "プラグインコマンド"
    permission: NekoHubv2.cmd.nekohubv2
    usage: '/<command> <reload>'
  as:
    aliases: ["sudo"]
    description: "代行実行"
    permission: NekoHubv2.cmd.as
    usage: "/<command> <target> <cmd>"
  prefix:
    description: "プレフィックスをセットします。"
    permission: "NekoHubv2.cmd.prefix"
    usage: |
      /<command> [<target> <prefix>]

permissions:
  NekoHubv2:
    children:
      - NekoHubv2.cmd

  NekoHubv2.cmd:
    default: op

    children:
      - NekoHubv2.cmd.move
      - NekoHubv2.cmd.serverpanel
      - NekoHubv2.cmd.stickmenu
      - NekoHubv2.cmd.stick
      - NekoHubv2.cmd.enderchest
      - NekoHubv2.cmd.rule
      - NekoHubv2.cmd.nekohubv2
      - NekoHubv2.cmd.as
      - NekoHubv2.cmd.prefix

  # ============================== #
  # Command perms                  #
  # ============================== #
  NekoHubv2.cmd.move:
    default: op

  NekoHubv2.cmd.serverpanel:
    default: true

  NekoHubv2.cmd.stickmenu:
    default: true

  NekoHubv2.cmd.stick:
    default: true

  NekoHubv2.cmd.enderchest:
    default: true

  NekoHubv2.cmd.rule:
    default: true

  NekoHubv2.cmd.nekohubv2:
    default: op

  NekoHubv2.cmd.as:
    default: op

  NekoHubv2.cmd.prefix:
    default: op